### ISSUE TITLE
A way for OpenHacks to display their status

### ISSUE THREAD

**Issue by qrush** [OpenHack/openhack.github.com#71]
The main problem I have with the homepage of OpenHack is that it's difficult to tell which meetups are active, in progress, etc. I'm pretty sure we can put this metadata in the YAML frontmatter of each page in Jekyll...so for example:

``` yaml

---
layout: default
title: OpenHack - Buffalo
status: active

---
```

And then we can display that on the home page. I need to double check my Jekyll wizardry, but even a rake task to do this would work. 

What statuses would there be? I'm thinking:
- Preparing (Looking to organize, no dates set yet)
- Active (Meetups actively scheduled)
- Inactive (Meetups held in the past, no future meetups scheduled currently)
